spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3307/student_system?serverTimezone=Asia/Shanghai&useSSL=true&useUnicode=true
    username: root
    password: root
  flyway:
    encoding: utf-8
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3307/student_system?serverTimezone=Asia/Shanghai&useSSL=true&useUnicode=true
    username: root
    password: root